// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3360.VIKing.commands.AutoCommands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3360.VIKing.Robot;
import org.usfirst.frc3360.VIKing.subsystems.TankDrive;

/**
 *
 */
public class AutonomousDriveWithVBus extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	double speedR;
	double speedL;
	long startTimeMs;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousDriveWithVBus(double rVal, double lVal) {
    	speedR =rVal;
    	speedL = lVal;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	requires(Robot.tankDrive);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	startTimeMs = System.currentTimeMillis();
    	Robot.tankDrive.setControlMode(2);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	

    	Robot.tankDrive.setDriveValue(speedR, speedL);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	exit();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	exit();
    }
    private void exit(){
    	double error;
    	Robot.tankDrive.setDriveValue(0, 0);
    	System.out.println("Exit auto drive");
    	error = Math.sin(Robot.tankDrive.getOffsetDeg())* 40;
		Robot.HorizontalOffset += error;
    	//Robot.tankDrive.resetEncoderDistance();
    }
}
