// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3360.VIKing.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3360.VIKing.Robot;

/**
 * Set the arm to to requested angle using PID
 */
public class KillerWedgeAutoHandle extends Command {

	double anglePosition;
	String shootPosition; 
   
    public KillerWedgeAutoHandle(double anglePos, String shootPos) {
    
    	this.anglePosition = anglePos;
    	this.shootPosition = shootPos;
    	
    	requires(Robot.killerWedge);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	Robot.killerWedge.setKillerWedgePos(anglePosition, shootPosition);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	
    }
}
